import { NextRequest, NextResponse } from "next/server";
import { sendSMS, getMessage } from "@/lib/ringcentral";
import { saveConversation, getConversationHistory, formatPhoneE164 } from "@/lib/conversation";
import { generateEmmaResponse } from "@/lib/emma";
import { supabase } from "@/lib/supabase";

const DR_CAI_PHONE = "+18083083879";

export async function POST(req: NextRequest) {
  try {
    // RingCentral Webhook Validation Handshake
    const validationToken = req.headers.get("validation-token");
    if (validationToken) {
      console.log("RingCentral Webhook Validation handshake triggered!");
      return new NextResponse("OK", {
        status: 200,
        headers: {
          "Validation-Token": validationToken,
        },
      });
    }

    const body = await req.json();

    console.log("========== INCOMING SMS ==========");
    console.log(JSON.stringify(body, null, 2));

    const messageId = body?.body?.changes?.[0]?.newMessageIds?.[0];

    if (!messageId) {
      return NextResponse.json({
        success: true,
        skipped: true,
      });
    }

    console.log("MESSAGE ID:", messageId);

    const sms = await getMessage(String(messageId));

    const direction = sms.direction || "Inbound";
    const rawPhone = direction === "Inbound"
      ? (sms.from?.phoneNumber || "")
      : (sms.to?.[0]?.phoneNumber || "");
    const phone = formatPhoneE164(rawPhone);
    const message = sms.subject || sms.text || "";

    const cleanPhone = phone.replace(/\D/g, "");
    const cleanPhone10 = cleanPhone.slice(-10);

    // Outbound Interceptor for Human Takeover
    if (direction !== "Inbound") {
      console.log(`[Outbound SMS] Sent to patient: ${phone} - "${message}"`);
      
      if (phone) {
        // Check if this text was already logged (which means it was generated by Emma)
        const { data: lastLogged } = await supabase
          .from("sms_conversations")
          .select("*")
          .eq("phone", phone)
          .eq("role", "assistant")
          .order("created_at", { ascending: false })
          .limit(5);

        const alreadyLogged = lastLogged?.some((msg: any) => msg.message === message);

        if (!alreadyLogged) {
          console.log(`[Human Takeover] Manual SMS sent by staff. Pausing Emma and clearing pending same-day request for ${phone}.`);
          
          // 1. Log the human message in the history
          await saveConversation(phone, "assistant", message);

          // 2. Set pause_emma to true and clear pending_human_reply in the leads table
          try {
            await supabase
              .from("leads")
              .update({ 
                pause_emma: true,
                pending_human_reply: false
              })
              .or(`phone.eq.${phone},phone.eq.${cleanPhone},phone.eq.${cleanPhone10},phone.ilike.%${cleanPhone10}%`);
          } catch (err: any) {
            console.error("Failed to update takeover flags in database:", err.message);
          }
        }

        // Check if human explicitly wants to resume Emma
        if (message && /resume emma|开启emma|\/resume/i.test(message)) {
          console.log(`[Human Handback] Staff requested to resume Emma for ${phone}.`);
          try {
            await supabase
              .from("leads")
              .update({ 
                pause_emma: false,
                pending_human_reply: false
              })
              .or(`phone.eq.${phone},phone.eq.${cleanPhone},phone.eq.${cleanPhone10},phone.ilike.%${cleanPhone10}%`);
          } catch (err: any) {
            console.error("Failed to update pause_emma column:", err.message);
          }
        }
      }

      return NextResponse.json({
        success: true,
        loggedOutbound: true,
      });
    }

    console.log("FULL SMS:", JSON.stringify(sms, null, 2));

    // Validate if the number exists in the database (leads, appointments, appointment_history)
    let existsInDb = false;

    if (cleanPhone10) {
      const [leadCheck, apptCheck, historyCheck] = await Promise.all([
        supabase
          .from("leads")
          .select("id")
          .or(`phone.eq.${phone},phone.eq.${cleanPhone},phone.eq.${cleanPhone10},phone.ilike.%${cleanPhone10}%`)
          .limit(1)
          .maybeSingle(),
        supabase
          .from("appointments")
          .select("id")
          .or(`phone.eq.${phone},phone.eq.${cleanPhone},phone.eq.${cleanPhone10},phone.ilike.%${cleanPhone10}%`)
          .limit(1)
          .maybeSingle(),
        supabase
          .from("appointment_history")
          .select("id")
          .or(`phone.eq.${phone},phone.eq.${cleanPhone},phone.eq.${cleanPhone10},phone.ilike.%${cleanPhone10}%`)
          .limit(1)
          .maybeSingle()
      ]);

      if (leadCheck.data || apptCheck.data || historyCheck.data) {
        existsInDb = true;
      }
    }

    if (!existsInDb) {
      console.log(`Stranger detection: number ${phone} is not in database. Deleting orphaned conversations and skipping response.`);
      if (cleanPhone10) {
        await supabase
          .from("sms_conversations")
          .delete()
          .or(`phone.eq.${phone},phone.eq.${cleanPhone},phone.eq.${cleanPhone10},phone.ilike.%${cleanPhone10}%`);
      }
      return NextResponse.json({
        success: true,
        skippedStranger: true,
        message: "Stranger number skipped and memory sync cleanup done."
      });
    }

    // Check if there is pre-existing conversation history (prior to this webhook event)
    const existingHistory = await getConversationHistory(phone, 1);
    const hasHistory = existingHistory && existingHistory.length > 0;

    // Detect if this message is a voicemail notification or call message
    const isVoicemailOrCall = 
      sms.type === "VoiceMail" ||
      (message && /voicemail|voice mail|missed call|left a message|语音留言|电话留言|未接来电|未接电话/i.test(message));

    if (isVoicemailOrCall && !hasHistory) {
      console.log(`Voicemail/call suppression: voicemail received from ${phone} but no existing chat history. Saving to DB for record-keeping but skipping reply.`);
      // Save user message to database for records
      await saveConversation(phone, "user", message);
      return NextResponse.json({
        success: true,
        skippedVoicemailNoHistory: true,
        message: "Voicemail skipped because there is no pre-existing chat history."
      });
    }

    // 1. Save user message to database
    await saveConversation(phone, "user", message);

    // Opt-out / Opt-in Interceptor
    const cleanPhoneCheck = phone.replace(/\D/g, "");
    const cleanPhoneCheck10 = cleanPhoneCheck.slice(-10);

    let isOptedOut = false;
    let isEmmaPaused = false;
    let existingLeadCheck: any = null;
    try {
      const { data: dbLead } = await supabase
        .from("leads")
        .select("*")
        .or(`phone.eq.${phone},phone.eq.${cleanPhoneCheck},phone.eq.${cleanPhoneCheck10},phone.ilike.%${cleanPhoneCheck10}%`)
        .limit(1)
        .maybeSingle();

      if (dbLead) {
        existingLeadCheck = dbLead;
        isOptedOut = dbLead.is_opted_out || dbLead.status === "OPTED_OUT";
        isEmmaPaused = !!dbLead.pause_emma;
      }
    } catch (lookupErr) {
      console.error("Error looking up lead for opt-out check:", lookupErr);
    }

    const optOutKeywords = /\b(STOP|UNSUBSCRIBE|QUIT|END)\b|明确不需要|不要再发了|不需要了|拒收/i;
    const optInKeywords = /\b(START|UNSTOP|RESUME|SUBSCRIBE)\b|恢复|重新订阅|恢复回复|开启/i;

    const matchesOptOut = optOutKeywords.test(message);
    const matchesOptIn = optInKeywords.test(message);

    if (matchesOptOut) {
      console.log(`Opt-out keyword triggered for ${phone}: "${message}"`);
      if (existingLeadCheck) {
        const { error: updateErr } = await supabase
          .from("leads")
          .update({
            is_opted_out: true,
            status: "OPTED_OUT",
            notes: existingLeadCheck.notes 
              ? `${existingLeadCheck.notes}\nUser opted out via SMS on ${new Date().toLocaleString()}`
              : `User opted out via SMS on ${new Date().toLocaleString()}`
          })
          .eq("id", existingLeadCheck.id);

        if (updateErr && updateErr.message.includes("is_opted_out") && updateErr.message.includes("does not exist")) {
          console.log("is_opted_out column does not exist yet. Retrying update without it.");
          await supabase
            .from("leads")
            .update({
              status: "OPTED_OUT",
              notes: existingLeadCheck.notes 
                ? `${existingLeadCheck.notes}\nUser opted out via SMS on ${new Date().toLocaleString()}`
                : `User opted out via SMS on ${new Date().toLocaleString()}`
            })
            .eq("id", existingLeadCheck.id);
        }
      } else {
        const { error: insertErr } = await supabase
          .from("leads")
          .insert({
            phone,
            name: sms.from?.name || "Patient",
            status: "OPTED_OUT",
            is_opted_out: true,
            notes: `Created opted-out lead via SMS on ${new Date().toLocaleString()}`
          });

        if (insertErr && insertErr.message.includes("is_opted_out") && insertErr.message.includes("does not exist")) {
          console.log("is_opted_out column does not exist yet. Retrying insert without it.");
          await supabase
            .from("leads")
            .insert({
              phone,
              name: sms.from?.name || "Patient",
              status: "OPTED_OUT",
              notes: `Created opted-out lead via SMS on ${new Date().toLocaleString()}`
            });
        }
      }

      const optOutReply = "You have successfully opted out. We will not send you any more automated messages. Text START to resume.";
      await sendSMS(phone, optOutReply);
      await saveConversation(phone, "assistant", optOutReply);

      return NextResponse.json({ success: true, optedOut: true });
    }

    if (matchesOptIn) {
      console.log(`Opt-in keyword triggered for ${phone}: "${message}"`);
      if (existingLeadCheck) {
        const { error: updateErr } = await supabase
          .from("leads")
          .update({
            is_opted_out: false,
            status: "CONTACTED",
            notes: existingLeadCheck.notes 
              ? `${existingLeadCheck.notes}\nUser opted in via SMS on ${new Date().toLocaleString()}`
              : `User opted in via SMS on ${new Date().toLocaleString()}`
          })
          .eq("id", existingLeadCheck.id);

        if (updateErr && updateErr.message.includes("is_opted_out") && updateErr.message.includes("does not exist")) {
          console.log("is_opted_out column does not exist yet. Retrying opt-in update without it.");
          await supabase
            .from("leads")
            .update({
              status: "CONTACTED",
              notes: existingLeadCheck.notes 
                ? `${existingLeadCheck.notes}\nUser opted in via SMS on ${new Date().toLocaleString()}`
                : `User opted in via SMS on ${new Date().toLocaleString()}`
            })
            .eq("id", existingLeadCheck.id);
        }
      }
      isOptedOut = false;
    }

    if (isOptedOut) {
      console.log(`Ignoring SMS from opted-out number ${phone}: "${message}"`);
      return NextResponse.json({ success: true, skippedOptedOut: true });
    }

    // Auto-set status to "answered" if they reply and are currently in a lead status
    if (existingLeadCheck) {
      const activeStatuses = [
        "NEW", "CONTACTED", "contacted", 
        "no respond", "no show", 
        "following up 1", "following up 2", "following up 3", "following up 4",
        "NO_RESPOND", "NO_SHOW", 
        "FOLLOWING_UP_1", "FOLLOWING_UP_2", "FOLLOWING_UP_3", "FOLLOWING_UP_4",
        "NO RESPOND", "NO SHOW", 
        "FOLLOWING UP 1", "FOLLOWING UP 2", "FOLLOWING UP 3", "FOLLOWING UP 4"
      ];
      if (activeStatuses.includes(existingLeadCheck.status)) {
        console.log(`Updating lead ${existingLeadCheck.id} status to answered because they replied.`);
        try {
          await supabase
            .from("leads")
            .update({ status: "answered" })
            .eq("id", existingLeadCheck.id);
        } catch (err: any) {
          console.error("Failed to update status to answered:", err.message);
        }
      }
    }

    // Same-day appointment request interceptor
    const sameDayRegex = /\b(today|same[\s-]*day|tonight|this[\s-]+afternoon|openings?[\s-]+today|get[\s-]+in[\s-]+today)\b|当天|今天|下半天/i;
    const cancelOrReschedRegex = /cancel|cancell|resched/i;
    const isSameDayRequest = message && sameDayRegex.test(message) && !cancelOrReschedRegex.test(message);

    if (isSameDayRequest) {
      console.log(`[Same-Day Escalation] Urgent request from ${phone}: "${message}"`);
      
      const patientDisplayName = existingLeadCheck?.name || sms.from?.name || "Patient";

      // 1. Pause Emma and set pending human reply flags in database
      try {
        await supabase
          .from("leads")
          .update({ 
            pause_emma: true,
            pending_human_reply: true,
            same_day_requested_at: new Date().toISOString()
          })
          .or(`phone.eq.${phone},phone.eq.${cleanPhoneCheck},phone.eq.${cleanPhoneCheck10},phone.ilike.%${cleanPhoneCheck10}%`);
      } catch (err: any) {
        console.error("Failed to update same-day flags in database:", err.message);
      }

      // 2. Alert Dr. Cai immediately via SMS
      const alertMsg = `🚨 URGENT SAME-DAY REQUEST! ${patientDisplayName} (${phone}) texted: "${message}". Emma has paused. Please reply to them immediately!`;
      try {
        await sendSMS(DR_CAI_PHONE, alertMsg);
        console.log(`[Same-Day Escalation] Alert sent to Dr. Cai for ${phone}`);
      } catch (err: any) {
        console.error("Failed to send same-day SMS alert to Dr. Cai:", err.message);
      }

      return NextResponse.json({
        success: true,
        forwardedToHuman: true,
        message: "Same-day request forwarded to human staff. Emma paused."
      });
    }

    if (isEmmaPaused) {
      console.log(`[Emma Paused] AI is paused for patient ${phone} because human took over. Ignoring inbound message: "${message}"`);
      return NextResponse.json({
        success: true,
        skippedEmmaPaused: true,
        message: "Emma is paused for this patient because a human has taken over."
      });
    }

    // 2. Classify intent via booking-agent
    const bookingResponse = await fetch(
      `${process.env.NEXT_PUBLIC_SITE_URL}/api/booking-agent`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          phone,
          message,
        }),
      }
    );

    const bookingResult = await bookingResponse.json();
    console.log("BOOKING RESULT:", JSON.stringify(bookingResult, null, 2));

    // Look up patient name from leads or appointments table for personalized experience
    let patientName = sms.from?.name || "Patient";
    let leadRecord: any = null;
    try {
      const cleanPhone = phone.replace(/\D/g, "");
      const cleanPhone10 = cleanPhone.slice(-10);

      // Search leads table first
      const { data: dbLead } = await supabase
        .from("leads")
        .select("*")
        .or(`phone.eq.${cleanPhone},phone.eq.${cleanPhone10},phone.ilike.%${cleanPhone10}%`)
        .limit(1)
        .maybeSingle();

      if (dbLead) {
        leadRecord = dbLead;
        patientName = dbLead.name || patientName;
        
        // Update slots in the leads table if new ones are extracted
        const updates: any = {};
        if (bookingResult.slots?.name && (!dbLead.name || dbLead.name === "Patient" || dbLead.name === "Unknown")) {
          updates.name = bookingResult.slots.name;
          patientName = bookingResult.slots.name;
        }
        if (bookingResult.slots?.dob && !dbLead.dob) {
          updates.dob = bookingResult.slots.dob;
        }
        if (bookingResult.slots?.insurance_type && !dbLead.insurance_type) {
          updates.insurance_type = bookingResult.slots.insurance_type;
        }
        if (bookingResult.slots?.insurance_carrier && !dbLead.insurance_carrier) {
          updates.insurance_carrier = bookingResult.slots.insurance_carrier;
        }
        if (bookingResult.slots?.claim_number && !dbLead.claim_number) {
          updates.claim_number = bookingResult.slots.claim_number;
        }
        if (bookingResult.slots?.location && !dbLead.location) {
          updates.location = bookingResult.slots.location;
        }

        if (Object.keys(updates).length > 0) {
          console.log(`Saving dynamic slots to DB for lead ${dbLead.id}:`, updates);
          const { data: updatedLead } = await supabase
            .from("leads")
            .update(updates)
            .eq("id", dbLead.id)
            .select()
            .maybeSingle();
          if (updatedLead) {
            leadRecord = updatedLead;
          }
        }
      }

      // 2.5 Aiea Location Escalation
      const isAieaSelected = 
        (bookingResult.slots?.location && bookingResult.slots.location.toLowerCase().includes("aiea")) ||
        (leadRecord?.location && leadRecord.location.toLowerCase().includes("aiea")) ||
        (/\baiea\b/i.test(message));

      if (isAieaSelected) {
        console.log(`[Aiea Intercept] Patient ${patientName} (${phone}) requested Aiea location. Pausing Emma.`);
        
        // 1. Pause Emma and set pending human reply flags in database
        try {
          await supabase
            .from("leads")
            .update({ 
              pause_emma: true,
              pending_human_reply: true,
              location: "Aiea",
              same_day_requested_at: new Date().toISOString()
            })
            .or(`phone.eq.${phone},phone.eq.${cleanPhoneCheck},phone.eq.${cleanPhoneCheck10},phone.ilike.%${cleanPhoneCheck10}%`);
        } catch (err: any) {
          console.error("Failed to update Aiea location flags in database:", err.message);
        }

        // 2. Alert Dr. Cai immediately via SMS
        const alertMsg = `🚨 AIEA LOCATION ESCALATION! ${patientName} (${phone}) requested Aiea clinic: "${message}". Emma has paused. Please reply to them manually!`;
        try {
          await sendSMS(DR_CAI_PHONE, alertMsg);
          console.log(`[Aiea Intercept] Alert sent to Dr. Cai for ${phone}`);
        } catch (err: any) {
          console.error("Failed to send Aiea escalation SMS alert to Dr. Cai:", err.message);
        }

        return NextResponse.json({
          success: true,
          forwardedToHuman: true,
          reason: "AIEA_LOCATION",
          message: "Aiea clinic requested. Forwarded to human staff. Emma paused."
        });
      }

      // Human takeover escalation for CANCEL_APPOINTMENT, TRANSFER_TO_HUMAN, and UNKNOWN intents
      const isHumanTransfer = ["TRANSFER_TO_HUMAN", "CANCEL_APPOINTMENT", "UNKNOWN"].includes(bookingResult.intent);
      if (isHumanTransfer) {
        console.log(`[Human Handover] Intent is ${bookingResult.intent} for ${phone}. Pausing Emma.`);
        
        // 1. Pause Emma and set pending human reply flags in database
        try {
          await supabase
            .from("leads")
            .update({ 
              pause_emma: true,
              pending_human_reply: true,
              same_day_requested_at: new Date().toISOString()
            })
            .or(`phone.eq.${phone},phone.eq.${cleanPhoneCheck},phone.eq.${cleanPhoneCheck10},phone.ilike.%${cleanPhoneCheck10}%`);
        } catch (err: any) {
          console.error("Failed to update human takeover flags in database:", err.message);
        }

        // 2. Alert Dr. Cai immediately via SMS
        let alertMsg = `🚨 HUMAN HELP REQUEST! ${patientName} (${phone}) texted: "${message}". Emma has paused. Please reply to them!`;
        if (bookingResult.intent === "CANCEL_APPOINTMENT") {
          alertMsg = `🚨 CANCELLATION REQUEST! ${patientName} (${phone}) texted: "${message}". Emma has paused. Please reply to them!`;
        }
        
        try {
          await sendSMS(DR_CAI_PHONE, alertMsg);
          console.log(`[Human Handover] Alert sent to Dr. Cai for ${phone}`);
        } catch (err: any) {
          console.error("Failed to send human handover SMS alert to Dr. Cai:", err.message);
        }

        return NextResponse.json({
          success: true,
          forwardedToHuman: true,
          message: `Request forwarded to human staff due to intent: ${bookingResult.intent}. Emma paused.`
        });
      } else {
        // If lead doesn't exist, create a new lead and save the extracted slots
        console.log(`Creating new lead for incoming phone ${phone} with slots.`);
        const initialName = bookingResult.slots?.name && bookingResult.slots.name !== "Patient" && bookingResult.slots.name !== "Unknown"
          ? bookingResult.slots.name
          : (sms.from?.name && sms.from.name !== "Unknown" ? sms.from.name : "Patient");
          
        const { data: newLead, error: insertError } = await supabase
          .from("leads")
          .insert({
            phone,
            name: initialName,
            status: "NEW",
            source: "SMS",
            notes: "Created automatically from incoming SMS.",
            dob: bookingResult.slots?.dob || null,
            insurance_type: bookingResult.slots?.insurance_type || null,
            insurance_carrier: bookingResult.slots?.insurance_carrier || null,
            claim_number: bookingResult.slots?.claim_number || null,
            location: bookingResult.slots?.location || null,
          })
          .select()
          .maybeSingle();

        if (newLead) {
          leadRecord = newLead;
          patientName = newLead.name;
        } else {
          console.error("Failed to create new lead for incoming SMS:", insertError);
          
          // Fallback to appointments table if lead creation fails
          const { data: dbAppt } = await supabase
            .from("appointments")
            .select("patient_name")
            .or(`phone.eq.${cleanPhone},phone.eq.${cleanPhone10},phone.ilike.%${cleanPhone10}%`)
            .limit(1)
            .maybeSingle();
          if (dbAppt?.patient_name) {
            patientName = dbAppt.patient_name;
          }
        }
      }
    } catch (lookupErr) {
      console.error("Patient name / lead lookup and update error:", lookupErr);
    }

    // 3. Check if there are attachments (photos/documents)
    const hasAttachments = sms.attachments && sms.attachments.some(
      (att: any) => 
        (att.contentType && (
          att.contentType.startsWith("image/") || 
          att.contentType.startsWith("application/")
        )) ||
        att.type === "MmsAttachment"
    );

    if (hasAttachments) {
      console.log("Inbound message has attachments. Triggering human handoff and doctor notification...");
      
      const humanMessage = bookingResult.language === "Chinese"
        ? `收到！${patientName !== "Patient" ? `${patientName}，` : ""}我已经收到了您发送的图片，并转发给了我们诊所的工作人员。工作人员在确认保险及证件后会尽快与您联系。如有其他问题，欢迎致电 808-528-7177。`
        : bookingResult.language === "Spanish"
        ? `¡Recibido! ${patientName !== "Patient" ? `${patientName}, h` : "H"}e recibido las imágenes de sus documentos y las he enviado a nuestro personal. Alguien se comunicará con usted poco después de verificar su cobertura. Si tiene alguna duda, puede llamarnos al 808-528-7177.`
        : bookingResult.language === "Japanese"
        ? `受信しました！${patientName !== "Patient" ? `${patientName}様、` : ""}ご送付いただいた画像を受け取り、当院のスタッフへ転送いたしました。スタッフが保険等の確認を行い、折り返しご連絡いたします。ご不明な点がございましたら 808-528-7177 までお電話ください。`
        : bookingResult.language === "Korean"
        ? `수신되었습니다! ${patientName !== "Patient" ? `${patientName} 님, ` : ""}보내주신 사진을 수령하여 저희 직원에게 전달했습니다. 보험 및 신원 확인 후 곧 연락드리겠습니다. 문의 사항이 있으시면 808-528-7177로 전화해 주세요.`
        : `Received! ${patientName !== "Patient" ? `${patientName}, I` : "I"} have received your pictures and forwarded them to our office staff. Someone will verify your details and contact you shortly. If you have any questions, feel free to call us at 808-528-7177.`;

      // Send to patient
      await sendSMS(phone, humanMessage);
      await saveConversation(phone, "assistant", humanMessage);

      // Notify the doctor
      await sendSMS(
        DR_CAI_PHONE,
        `
NEW ATTACHMENT
Patient: ${patientName} (${phone})
Sent photos/documents (e.g. insurance card/ID). Please check the RingCentral message store.
`
      );

      return NextResponse.json({ success: true, attachmentHandoff: true });
    }

    let actionResult: any = null;

    // 4. Perform transactional database/calendar operations based on intent
    if (bookingResult.intent === "BOOK_APPOINTMENT") {
      if (bookingResult.day && bookingResult.time) {
        try {
          const createResponse = await fetch(
            `${process.env.NEXT_PUBLIC_SITE_URL}/api/create-booking`,
            {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                patientName,
                phone,
                day: bookingResult.day,
                time: bookingResult.time,
              }),
            }
          );

          const createResult = await createResponse.json();
          if (createResult.success) {
            actionResult = {
              success: true,
              action: "BOOK",
              appointmentTime: `${bookingResult.day} at ${bookingResult.time}`,
              serviceType: createResult.serviceType,
            };

            // Update lead status in leads table to BOOKED if they are a lead
            if (leadRecord) {
              const { error: updateLeadError } = await supabase
                .from("leads")
                .update({
                  status: "BOOKED",
                  notes: leadRecord.notes 
                    ? `${leadRecord.notes}\nLead successfully booked appointment on ${new Date().toLocaleString()}`
                    : `Lead successfully booked appointment on ${new Date().toLocaleString()}`,
                })
                .eq("id", leadRecord.id);

              if (updateLeadError) {
                console.error("Error updating lead to BOOKED status:", updateLeadError);
              } else {
                console.log(`Lead status successfully updated to BOOKED for lead ${leadRecord.id}`);
              }
            }
          } else {
            actionResult = {
              success: false,
              action: "BOOK",
              reason: createResult.reason || "FULL",
            };
          }
        } catch (err: any) {
          console.error("Booking transaction failed:", err);
          actionResult = {
            success: false,
            action: "BOOK",
            reason: "ERROR",
          };
        }
      }
    } else if (bookingResult.intent === "RESCHEDULE_APPOINTMENT") {
      if (bookingResult.day && bookingResult.time) {
        try {
          const nowHonolulu = new Date(new Date().toLocaleString("en-US", { timeZone: "Pacific/Honolulu" }));
          const nextDate = new Date(nowHonolulu);
          const dayMap: Record<string, number> = {
            Sunday: 0,
            Monday: 1,
            Tuesday: 2,
            Wednesday: 3,
            Thursday: 4,
            Friday: 5,
            Saturday: 6,
          };

          const targetDay = dayMap[bookingResult.day];
          if (targetDay === undefined) {
            throw new Error(`Invalid reschedule day: ${bookingResult.day}`);
          }

          while (nextDate.getDay() !== targetDay) {
            nextDate.setDate(nextDate.getDate() + 1);
          }

          const hour = parseInt(bookingResult.time);
          const yyyy = nextDate.getFullYear();
          const mm = String(nextDate.getMonth() + 1).padStart(2, "0");
          const dd = String(nextDate.getDate()).padStart(2, "0");
          const hh = String(hour).padStart(2, "0");
          let startTime = `${yyyy}-${mm}-${dd}T${hh}:00:00-10:00`;

          // Past Time Prevention: if the rescheduled time has already passed today, move it to next week
          const resolvedDate = new Date(startTime);
          if (resolvedDate < nowHonolulu) {
            console.log(`Resolved reschedule time ${startTime} is in the past. Shifting forward by 7 days.`);
            nextDate.setDate(nextDate.getDate() + 7);
            const newYyyy = nextDate.getFullYear();
            const newMm = String(nextDate.getMonth() + 1).padStart(2, "0");
            const newDd = String(nextDate.getDate()).padStart(2, "0");
            startTime = `${newYyyy}-${newMm}-${newDd}T${hh}:00:00-10:00`;
          }

          const rescheduleResponse = await fetch(
            `${process.env.NEXT_PUBLIC_SITE_URL}/api/reschedule-appointment`,
            {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({
                phone,
                startTime,
              }),
            }
          );

          const rescheduleResult = await rescheduleResponse.json();
          if (rescheduleResult.success) {
            actionResult = {
              success: true,
              action: "RESCHEDULE",
              appointmentTime: `${bookingResult.day} at ${bookingResult.time}`,
            };
          } else {
            actionResult = {
              success: false,
              action: "RESCHEDULE",
              reason: rescheduleResult.reason || "FAILED",
            };
          }
        } catch (err: any) {
          console.error("Reschedule transaction failed:", err);
          actionResult = {
            success: false,
            action: "RESCHEDULE",
            reason: "ERROR",
          };
        }
      }
    } else if (bookingResult.intent === "CANCEL_APPOINTMENT") {
      try {
        const cancelResponse = await fetch(
          `${process.env.NEXT_PUBLIC_SITE_URL}/api/cancel-appointment`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              phone,
            }),
          }
        );

        const cancelResult = await cancelResponse.json();
        if (cancelResult.success) {
          actionResult = {
            success: true,
            action: "CANCEL",
          };
        } else {
          actionResult = {
            success: false,
            action: "CANCEL",
            reason: "FAILED",
          };
        }
      } catch (err: any) {
        console.error("Cancel transaction failed:", err);
        actionResult = {
          success: false,
          action: "CANCEL",
          reason: "ERROR",
        };
      }
    }

    // 5. Retrieve available timeslots dynamically (Only for Class B/C booking-oriented intents)
    const bookingIntents = [
      "BOOK_APPOINTMENT",
      "CHECK_AVAILABILITY",
      "RESCHEDULE_APPOINTMENT",
      "AVAILABILITY_QUESTION",
      "NEW_LEAD_OUTREACH"
    ];
    const needsSlots = bookingIntents.includes(bookingResult.intent) || 
                       ["KB_ANSWER", "INSURANCE_QUESTION", "SERVICE_QUESTION", "PRICE_QUESTION"].includes(bookingResult.intent);

    let availableSlots: string[] = [];
    if (needsSlots) {
      try {
        const slotsUrl = bookingResult.day
          ? `${process.env.NEXT_PUBLIC_SITE_URL}/api/find-slots?day=${bookingResult.day}`
          : `${process.env.NEXT_PUBLIC_SITE_URL}/api/find-slots`;
        
        const slotsResponse = await fetch(slotsUrl);
        const slotsResult = await slotsResponse.json();
        availableSlots = slotsResult.slots || [];
      } catch (err) {
        console.error("Error fetching slots:", err);
      }
    }

    // 6. Query knowledge base if user has general/informational question (RAG - Class B only)
    let kbAnswer = "";
    let kbUrl = "";
    const kbIntents = [
      "KB_QUESTION",
      "CLINIC_INFO_QUESTION",
      "BUSINESS_HOURS_QUESTION",
      "LOCATION_QUESTION",
      "PRICE_QUESTION",
      "INSURANCE_QUESTION",
      "SERVICE_QUESTION",
      "NEW_PATIENT_QUESTION",
    ];

    if (bookingResult.intent === "KB_ANSWER") {
      kbAnswer = bookingResult.answer || "";
      kbUrl = bookingResult.url || "";
    } else if (kbIntents.includes(bookingResult.intent)) {
      try {
        const kbResponse = await fetch(
          `${process.env.NEXT_PUBLIC_SITE_URL}/api/search-kb`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              question: message,
            }),
          }
        );

        const kbResult = await kbResponse.json();
        if (kbResult.found) {
          kbAnswer = kbResult.answer || "";
          kbUrl = kbResult.url || "";
        }
      } catch (err) {
        console.error("KB Search failed:", err);
      }
    }

    // 6b. Secondary check: If no webpage URL is retrieved yet, but the user message mentions a disease/symptom/treatment, query search-kb specifically to fetch a webpage URL
    const diseaseKeywordsRegex = /(pain|sciatica|headache|migraine|stress|anxiety|insomnia|injury|shoulder|neck|back|knee|arthritis|痛|酸|失眠|压力|受伤|拔罐|cupping)/i;
    if (!kbUrl && diseaseKeywordsRegex.test(message)) {
      try {
        console.log(`Disease keyword detected in message: "${message}". Fetching URL fallback.`);
        const kbResponse = await fetch(
          `${process.env.NEXT_PUBLIC_SITE_URL}/api/search-kb`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              question: message,
            }),
          }
        );

        const kbResult = await kbResponse.json();
        if (kbResult.found && kbResult.url) {
          kbUrl = kbResult.url;
          if (!kbAnswer) {
            kbAnswer = kbResult.answer || "";
          }
        }
      } catch (err) {
        console.error("Secondary disease URL lookup failed:", err);
      }
    }

    // 7. Fetch conversation history for assistant reply generation context
    const conversationHistory = phone ? await getConversationHistory(phone, 6) : [];

    // 8. Generate a warm, human-like, database-backed response via Emma
    const replyMessage = await generateEmmaResponse({
      patientMessage: message,
      patientName,
      conversationHistory,
      intent: bookingResult.intent,
      language: bookingResult.language || "English",
      actionResult,
      kbAnswer,
      kbUrl,
      availableSlots,
      phone,
    });

    // 9. Customise JaneApp links and apply Medical Safety Guardrails (JaneApp customization temporarily disabled per user request)
    let finalReply = replyMessage;

    // Medical Safety Guardrail check
    const restrictedAcupoints = /\b(LI-?4|ST-?36|SP-?6|LV-?3|GB-?20|DU-?20|REN-?4)\b|(穴位|针灸穴|配穴|药方|中药配方)/i;
    if (restrictedAcupoints.test(finalReply)) {
      console.log("Restricted medical content / acupoint detected in reply. Triggering Guardrail fallback.");
      finalReply = bookingResult.language === "Chinese"
        ? "我无法通过短信提供具体的医疗建议或穴位选择。David Cai 医生会在您的一对一咨询中亲自评估您的状况。让我们先为您安排与他的会诊！"
        : "I cannot provide specific medical advice or acupoint selections via text. Dr. David Cai will personally evaluate your condition during your one-on-one consultation. Let's get you scheduled to see him first!";
    }

    // 10. Send SMS and save conversation
    await sendSMS(phone, finalReply);
    await saveConversation(phone, "assistant", finalReply);

    // 11. If the intent is TRANSFER_TO_HUMAN or UNKNOWN (fallback cases), notify the doctor
    const needsDoctorNotification = ["TRANSFER_TO_HUMAN", "UNKNOWN"].includes(bookingResult.intent);
    
    if (needsDoctorNotification) {
      console.log(`Intent is ${bookingResult.intent}. Notifying doctor for human assistance...`);
      
      // Notify the doctor via SMS
      await sendSMS(
        DR_CAI_PHONE,
        `
HUMAN HELP NEEDED
Patient: ${patientName} (${phone})
Message: "${message}"
Emma has replied and requested human staff follow-up.
`
      );
    }

    return NextResponse.json({
      success: true,
    });
  } catch (error: any) {
    console.error("sms webhook error", error);
    return NextResponse.json(
      {
        success: false,
        error: error.message,
      },
      {
        status: 500,
      }
    );
  }
}

// Helper to customize JaneApp URLs with dynamic slot query parameters
function customizeJaneAppUrls(
  text: string,
  slots: { name?: string; phone?: string; location?: string }
): string {
  return text.replace(/(https?:\/\/[^\s]*janeapp\.com[^\s]*)/gi, (url) => {
    try {
      // Remove trailing punctuation from url (like period, comma, or parenthesis)
      let cleanUrl = url;
      let suffix = "";
      const match = url.match(/([.,!?)]+)$/);
      if (match) {
        cleanUrl = url.slice(0, -match[1].length);
        suffix = match[1];
      }

      const urlObj = new URL(cleanUrl);
      if (slots.name && slots.name !== "Patient" && slots.name !== "Unknown") {
        urlObj.searchParams.set("name", slots.name);
      }
      if (slots.phone) {
        urlObj.searchParams.set("phone", slots.phone);
      }
      if (slots.location) {
        urlObj.searchParams.set("location", slots.location.toLowerCase());
      }
      return urlObj.toString() + suffix;
    } catch {
      return url;
    }
  });
}
